### ISSUE TITLE
opencv not responding

### ISSUE THREAD

**Issue by helios78971** [npq-thien/Vehicle_Detection_and_Counting_System#4]
i try to run it on linux, but every time its done the opencv window don't close automatically instead  it's not responding, and if i try to force quit, everything stop working

**Comment by npq-thien** [comment]
sorry. I am not familiar with linux, you can try to install opencv version 4.1.2 (that's my version i ran this project)

**Comment by Mandar1762** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'best_new.pt'

it gives this error

**Comment by helios78971** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'best_new.pt'
> 
> it gives this error

i think u should specify the location of the yolov5 model correctly

**Comment by npq-thien** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'best_new.pt'
> 
> it gives this error

It looks like i haven't uploaded the "best_new.pt". In file track.py at line 306, you can change the path default to another file weight like "best_200epoch.pt" or "best64.pt"
