### ISSUE TITLE
Changes to be made for RTSP stream

### ISSUE THREAD

**Issue by sundaram123krishnan** [npq-thien/Vehicle_Detection_and_Counting_System#5]
How can i run this code to work for an rtsp stream, rather than inputting any video?

**Comment by npq-thien** [comment]
What do you mean run RTSP ? You have a camera or something ?

**Comment by sundaram123krishnan** [comment]
Yaa i have a ip camera setup

**Comment by npq-thien** [comment]
https://www.youtube.com/watch?v=7gz3vUmy0C0&t=1692s&ab_channel=AI4LIFE
This is a video with original source code, it doesn't have Streamlit. Yolov5 itself can run detection through a webcam (you can see its arguments at the end of _track.py_ file). 
About the camera setup with another device, i haven't tried yet. Sorry

**Comment by sundaram123krishnan** [comment]
ok thx,
